services:
  nextjs-app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
        - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    env_file:
      - .env.local
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - IP_INFO_TOKEN=${IP_INFO_TOKEN}
      - LOGGER_EMAIL=${LOGGER_EMAIL}
      - NOVU_API_KEY=${NOVU_API_KEY}
      - NEXT_PUBLIC_NOVU_APP_IDENTIFIER=${NEXT_PUBLIC_NOVU_APP_IDENTIFIER}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "3000:3000"
